-- Seeds 10 time-limited (29-day) product keys, generated by
-- scripts/generate-timed-keys.js. Run once, after schema.sql (which must already
-- have the duration_days/expires_at columns), in Supabase's SQL Editor. Safe to
-- re-run: "on conflict do nothing" skips hashes already present instead of erroring.
-- Each key's access window starts the moment it's first activated, not now.

insert into public.license_keys (key_hash, duration_days) values
  ('60db4c0844e70902ededa1d9d13d906059bbc71e727d9b5e83908b39c4bf8340', 29),
  ('2a0927143dcb74232cc8f61a94f2b76d78ddbfc3c5cce0e98734fb99dcca103c', 29),
  ('c2b09bae1f582267a29623c6e0ee43ee383b52cae8b543f352d9e97d69341d77', 29),
  ('de560dbfde26839365fd8bf9ce6245226a3f9824727c6733c6cdd7cb763cbcb8', 29),
  ('3d075fa97c18d55bd99c3a614763de747c3caa373132df7308f4237f032e9df7', 29),
  ('daa50baeb416fd66152ef7fcac03940774ba23807a2a240f774d974ef16d9ecf', 29),
  ('89a2dc671ee60a49a927357287aa1bd22a75badc9c48af4099025dc7cbae861f', 29),
  ('f8b4e4d869cbc103b79144390dad4b75d3ecb92cf16957bfa3af7391dde07b8e', 29),
  ('cdd03e0aa16540b9e08457aea682650483ed39aea2cd723e3bd779431f60010e', 29),
  ('8afbb690af5b08b0c48a86a1ad2085500c23582185599295b34ab4a32eabb7c1', 29)
on conflict (key_hash) do nothing;
